defaults:
  - _self_
  - config: sim_module

hydra:
  run:
    dir: ${config.output_dir}/${hydra:job.name}-${now:%Y-%m-%d}/${now:%H-%M-%S}
config:
  # ying-tof
  # dark_path: '/nvme/siam_data/IAM_data/'
  # data_path: '/nvme/siam_data/train/source'
  # gt_path: '/nvme/siam_data/train/label1'
  # pred_data_path: '/nvme/siam_data/test/source'
  # pred_gt_path: '/nvme/siam_data/test/label1'
  
  # midas-tof
  # dark_path: '/nvme/MIDAS/IAM_data/'
  # data_path: '/nvme/MIDAS/train/rescale_source'
  # gt_path: '/nvme/MIDAS/train/label'
  # pred_data_path: '/nvme/MIDAS/test/rescale_source'
  # pred_gt_path: '/nvme/MIDAS/test/label'
  # pc
  dark_path: '/nvme/PCA/IAM_data/'
  data_path: '/nvme/PCA/train/rescale_source'
  gt_path: '/nvme/PCA/train/label'
  pred_data_path: '/nvme/PCA/test/rescale_source'
  pred_gt_path: '/nvme/PCA/test/label'
  #
  init_type: 'none'  # ['normal', 'xavier', 'xavier_uniform', 'kaiming', 'orthogonal', 'none]
  aug: False  # True or False
  epochs: 100
  epochs_per_checkpoint: 20
  batch_size: 4
  init_lr: 0.01
  scheduler_step_size: 20
  scheduler_gamma: 0.8
  cudnn_enabled: True
  cudnn_benchmark: True
  use_scheduler: True
  
  job_name: ${hydra:job.name}
  hydra_path: ${hydra:runtime.output_dir}